name: Playwright Tests
on:
  push:
    branches: [test_commons]
  pull_request:
    branches: [test_commons]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14.x"

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install playwright/test
        run: npm install -D @playwright/test

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
