name: Playwright Tests
on:
  push:
    branches: [test_commons]
  pull_request:
    branches: [test_commons]
jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2

      - uses: microsoft/playwright-github-action@v1

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install playwright/test
        run: npm install -D @playwright/test

      - name: Run Playwright tests
        run: npx playwright test
